### ISSUE TITLE
track() and monitor_external() return inconsistent responses

### ISSUE THREAD

**Issue by martindavis** [peterruggero/postmaster-php#16]
`Postmaster_Tracking::montior_external()` returns a pure JSON response.
`Postmaster_Tracking::track()` returns a `Postmaster_Object`.

This is quite unexpected with working with the library. What's the best way to fix this so we don't break people moving forward, but keep the library consistent for newcomers, such as myself?

**Comment by CountZachula** [comment]
Hey @martindavis,

Thanks for checking out Postmaster!

<code>Postmaster_Tracking::monitor_external()</code> is a <b>web hook subscription</b>. Therefore, the library itself does not act as an HTTP POST listener for the response (it has no visibility of it at all). Because of this, there is no way to serialize the JSON into a <code>Postmaster_Object</code>.

Are you requesting a helper feature to serialize a JSON response into a <code>Postmaster_Object</code>? This is something that your app would have to call after the listener has received the response.

Regards,
Z

**Comment by martindavis** [comment]
Hi @MorbidZach,

Thanks! It is pretty awesome what you can do with Postmaster!

Yes, I am requesting that feature. It took me completely off-guard that I should be expecting any kind of response at all when requesting a **web hook subscription**. My first reading of the docs lead me to believe if I submitted a package that was currently `In-Transit`, my app would immediately receive a web hook response with that information. It wasn't until the second time I read the docs that I realized the web hook responses would only come when packages change status. After experimenting with `monitor_external()`, I discovered it returns valid JSON that (as far as I can tell) is a `Postmaster_Object`. Since these are external packages, I have no way of knowing their status until I submit them to Postmaster.

Sure, my app can convert the response to a `Postmaster_Object`, but why not make it part of the library so that all requests act the exact same way? Did Postmaster change how this works recently?

This was a pain point implementing the library and I'm just trying to help other developers have an easier time.

**Comment by CountZachula** [comment]
@martindavis I've added a helper function to convert the initial web hook response to a Postmaster_Object. The usage is as follows:

```
$result = Postmaster_Tracking::monitor_external(array(
    "tracking_no" => "1ZW470V80310800043",
    "url" => "http://example.com/your-http-post-listener",
    "events" => ["Delivered", "Exception"]
));

$resultAsPostmasterObject = Postmaster_Tracking::toPostmaster_ExternalPackage($result);
var_dump($resultAsPostmasterObject);
```

One more thing to note: I was wrong about this functionality changing recently. See #15 for more details.
